sqlite3 instance/health.db <<EOF

INSERT INTO Goal (category, description, title, unit) VALUES 
('CKD', 'Drink 1.5 liters of water', 'Stay Hydrated!', 'L'),
('CKD', 'Limit sodium intake to 2g', 'Cut the Salt!', 'Grams'),
('CKD', 'Do 20 minutes of light exercise', 'Gentle Moves!', 'Min'),
('CKD', 'Eat 3 servings of low-potassium fruits', 'Fruit Power!', 'Servings'),
('CKD', 'Track daily blood pressure', 'Know Your Numbers!', 'Checks'),
('CKD', 'Avoid processed foods', 'Go Fresh!', 'Days'),
('CKD', 'Sleep at least 7 hours', 'Rest and Recover!', 'Hours'),
('CKD', 'Limit protein intake to 60g', 'Balanced Proteins!', 'Grams'),
('CKD', 'Practice 10 minutes of mindfulness', 'Relax Your Mind!', 'Min'),
('CKD', 'Prepare a low-sodium homemade meal', 'Healthy Cooking!', 'Meals'),
('general', 'Drink 8 glasses of water', 'Hydrate Yourself!', 'Glasses'),
('general', 'Walk 10,000 steps daily', 'Keep Moving!', 'Steps'),
('general', 'Sleep at least 8 hours', 'Recharge Your Body!', 'Hours'),
('general', 'Do 30 minutes of physical activity', 'Stay Active!', 'Min'),
('general', 'Eat 5 servings of fruits and vegetables', 'Healthy Bites!', 'Servings'),
('general', 'Meditate for 15 minutes', 'Calm Your Mind!', 'Min'),
('general', 'Limit screen time to 2 hours', 'Digital Detox!', 'Hours'),
('general', 'Practice deep breathing for 5 minutes', 'Breathe Easy!', 'Min'),
('general', 'Write down 3 positive things about your day', 'Gratitude Journal!', 'Entries'),
('general', 'Take a 10-minute stretching break', 'Stretch it Out!', 'Min'),
('diabetes', 'Drink at least 2 liters of water', 'Stay Hydrated!', 'L'),
('diabetes', 'Walk 5,000 steps daily', 'Step it up!', 'Steps'),
('diabetes', 'Eat 5 servings of vegetables', 'Go Green!', 'Servings'),
('diabetes', 'Sleep at least 7 hours', 'Rest Well!', 'Hours'),
('diabetes', 'Limit sugar intake to 25g', 'Sugar Cut!', 'Grams'),
('diabetes', 'Meditate for 10 minutes', 'Clear Your Mind!', 'Min'),
('diabetes', 'Check your blood sugar level', 'Know Your Numbers!', 'Checks'),
('diabetes', 'Avoid sugary drinks', 'Skip the Soda!', 'Days'),
('diabetes', 'Prepare a healthy homemade meal', 'Cook Healthy!', 'Meals'),
('diabetes', 'Do yoga for 20 minutes', 'Stretch and Relax!', 'Min');
EOF